# Generated by Django 5.0.7 on 2024-07-18 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_remove_codesubmission_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
